export const SURAHS = [
  { number: 1,   arabic: 'الفاتحة',    english: 'Al-Fatiha',      meaning: 'The Opening',          verses: 7   },
  { number: 2,   arabic: 'البقرة',     english: 'Al-Baqarah',     meaning: 'The Cow',              verses: 286 },
  { number: 3,   arabic: 'آل عمران',   english: "Ali 'Imran",     meaning: 'Family of Imran',      verses: 200 },
  { number: 4,   arabic: 'النساء',     english: 'An-Nisa',        meaning: 'The Women',            verses: 176 },
  { number: 5,   arabic: 'المائدة',    english: 'Al-Maidah',      meaning: 'The Table Spread',     verses: 120 },
  { number: 6,   arabic: 'الأنعام',    english: "Al-An'am",       meaning: 'The Cattle',           verses: 165 },
  { number: 7,   arabic: 'الأعراف',    english: "Al-A'raf",       meaning: 'The Heights',          verses: 206 },
  { number: 8,   arabic: 'الأنفال',    english: 'Al-Anfal',       meaning: 'The Spoils of War',    verses: 75  },
  { number: 9,   arabic: 'التوبة',     english: 'At-Tawbah',      meaning: 'The Repentance',       verses: 129 },
  { number: 10,  arabic: 'يونس',       english: 'Yunus',          meaning: 'Jonah',                verses: 109 },
  { number: 11,  arabic: 'هود',        english: 'Hud',            meaning: 'Hud',                  verses: 123 },
  { number: 12,  arabic: 'يوسف',       english: 'Yusuf',          meaning: 'Joseph',               verses: 111 },
  { number: 13,  arabic: 'الرعد',      english: "Ar-Ra'd",        meaning: 'The Thunder',          verses: 43  },
  { number: 14,  arabic: 'إبراهيم',    english: 'Ibrahim',        meaning: 'Abraham',              verses: 52  },
  { number: 15,  arabic: 'الحجر',      english: 'Al-Hijr',        meaning: 'The Rocky Tract',      verses: 99  },
  { number: 16,  arabic: 'النحل',      english: 'An-Nahl',        meaning: 'The Bee',              verses: 128 },
  { number: 17,  arabic: 'الإسراء',    english: "Al-Isra'",       meaning: 'The Night Journey',    verses: 111 },
  { number: 18,  arabic: 'الكهف',      english: 'Al-Kahf',        meaning: 'The Cave',             verses: 110 },
  { number: 19,  arabic: 'مريم',       english: 'Maryam',         meaning: 'Mary',                 verses: 98  },
  { number: 20,  arabic: 'طه',         english: 'Ta-Ha',          meaning: 'Ta-Ha',                verses: 135 },
  { number: 21,  arabic: 'الأنبياء',   english: "Al-Anbiya'",     meaning: 'The Prophets',         verses: 112 },
  { number: 22,  arabic: 'الحج',       english: 'Al-Hajj',        meaning: 'The Pilgrimage',       verses: 78  },
  { number: 23,  arabic: 'المؤمنون',   english: "Al-Mu'minun",    meaning: 'The Believers',        verses: 118 },
  { number: 24,  arabic: 'النور',      english: 'An-Nur',         meaning: 'The Light',            verses: 64  },
  { number: 25,  arabic: 'الفرقان',    english: 'Al-Furqan',      meaning: 'The Criterion',        verses: 77  },
  { number: 26,  arabic: 'الشعراء',    english: "Ash-Shu'ara'",   meaning: 'The Poets',            verses: 227 },
  { number: 27,  arabic: 'النمل',      english: 'An-Naml',        meaning: 'The Ant',              verses: 93  },
  { number: 28,  arabic: 'القصص',      english: 'Al-Qasas',       meaning: 'The Stories',          verses: 88  },
  { number: 29,  arabic: 'العنكبوت',   english: "Al-'Ankabut",    meaning: 'The Spider',           verses: 69  },
  { number: 30,  arabic: 'الروم',      english: 'Ar-Rum',         meaning: 'The Romans',           verses: 60  },
  { number: 31,  arabic: 'لقمان',      english: 'Luqman',         meaning: 'Luqman',               verses: 34  },
  { number: 32,  arabic: 'السجدة',     english: 'As-Sajdah',      meaning: 'The Prostration',      verses: 30  },
  { number: 33,  arabic: 'الأحزاب',    english: 'Al-Ahzab',       meaning: 'The Combined Forces',  verses: 73  },
  { number: 34,  arabic: 'سبأ',        english: "Saba'",          meaning: 'Sheba',                verses: 54  },
  { number: 35,  arabic: 'فاطر',       english: 'Fatir',          meaning: 'Originator',           verses: 45  },
  { number: 36,  arabic: 'يس',         english: 'Ya-Sin',         meaning: 'Ya-Sin',               verses: 83  },
  { number: 37,  arabic: 'الصافات',    english: 'As-Saffat',      meaning: 'Those Ranged in Rows', verses: 182 },
  { number: 38,  arabic: 'ص',          english: 'Sad',            meaning: 'The Letter Sad',       verses: 88  },
  { number: 39,  arabic: 'الزمر',      english: 'Az-Zumar',       meaning: 'The Troops',           verses: 75  },
  { number: 40,  arabic: 'غافر',       english: 'Ghafir',         meaning: 'The Forgiver',         verses: 85  },
  { number: 41,  arabic: 'فصلت',       english: 'Fussilat',       meaning: 'Explained in Detail',  verses: 54  },
  { number: 42,  arabic: 'الشورى',     english: 'Ash-Shuraa',     meaning: 'The Consultation',     verses: 53  },
  { number: 43,  arabic: 'الزخرف',     english: 'Az-Zukhruf',     meaning: 'The Ornaments of Gold',verses: 89  },
  { number: 44,  arabic: 'الدخان',     english: 'Ad-Dukhan',      meaning: 'The Smoke',            verses: 59  },
  { number: 45,  arabic: 'الجاثية',    english: 'Al-Jathiyah',    meaning: 'The Crouching',        verses: 37  },
  { number: 46,  arabic: 'الأحقاف',    english: 'Al-Ahqaf',       meaning: 'The Wind-Curved Sandhills', verses: 35 },
  { number: 47,  arabic: 'محمد',       english: 'Muhammad',       meaning: 'Muhammad',             verses: 38  },
  { number: 48,  arabic: 'الفتح',      english: 'Al-Fath',        meaning: 'The Victory',          verses: 29  },
  { number: 49,  arabic: 'الحجرات',    english: 'Al-Hujurat',     meaning: 'The Rooms',            verses: 18  },
  { number: 50,  arabic: 'ق',          english: 'Qaf',            meaning: 'The Letter Qaf',       verses: 45  },
  { number: 51,  arabic: 'الذاريات',   english: 'Adh-Dhariyat',   meaning: 'The Winnowing Winds',  verses: 60  },
  { number: 52,  arabic: 'الطور',      english: 'At-Tur',         meaning: 'The Mount',            verses: 49  },
  { number: 53,  arabic: 'النجم',      english: 'An-Najm',        meaning: 'The Star',             verses: 62  },
  { number: 54,  arabic: 'القمر',      english: 'Al-Qamar',       meaning: 'The Moon',             verses: 55  },
  { number: 55,  arabic: 'الرحمن',     english: 'Ar-Rahman',      meaning: 'The Beneficent',       verses: 78  },
  { number: 56,  arabic: 'الواقعة',    english: "Al-Waqi'ah",     meaning: 'The Inevitable',       verses: 96  },
  { number: 57,  arabic: 'الحديد',     english: 'Al-Hadid',       meaning: 'The Iron',             verses: 29  },
  { number: 58,  arabic: 'المجادلة',   english: 'Al-Mujadila',    meaning: 'The Pleading Woman',   verses: 22  },
  { number: 59,  arabic: 'الحشر',      english: 'Al-Hashr',       meaning: 'The Exile',            verses: 24  },
  { number: 60,  arabic: 'الممتحنة',   english: 'Al-Mumtahanah',  meaning: 'She That is to be Examined', verses: 13 },
  { number: 61,  arabic: 'الصف',       english: 'As-Saf',         meaning: 'The Ranks',            verses: 14  },
  { number: 62,  arabic: 'الجمعة',     english: "Al-Jumu'ah",     meaning: 'The Congregation',     verses: 11  },
  { number: 63,  arabic: 'المنافقون',  english: 'Al-Munafiqun',   meaning: 'The Hypocrites',       verses: 11  },
  { number: 64,  arabic: 'التغابن',    english: 'At-Taghabun',    meaning: 'The Mutual Disillusion',verses: 18 },
  { number: 65,  arabic: 'الطلاق',     english: 'At-Talaq',       meaning: 'The Divorce',          verses: 12  },
  { number: 66,  arabic: 'التحريم',    english: 'At-Tahrim',      meaning: 'The Prohibition',      verses: 12  },
  { number: 67,  arabic: 'الملك',      english: 'Al-Mulk',        meaning: 'The Sovereignty',      verses: 30  },
  { number: 68,  arabic: 'القلم',      english: 'Al-Qalam',       meaning: 'The Pen',              verses: 52  },
  { number: 69,  arabic: 'الحاقة',     english: "Al-Haqqah",      meaning: 'The Reality',          verses: 52  },
  { number: 70,  arabic: 'المعارج',    english: "Al-Ma'arij",     meaning: 'The Ascending Stairways', verses: 44 },
  { number: 71,  arabic: 'نوح',        english: 'Nuh',            meaning: 'Noah',                 verses: 28  },
  { number: 72,  arabic: 'الجن',       english: 'Al-Jinn',        meaning: 'The Jinn',             verses: 28  },
  { number: 73,  arabic: 'المزمل',     english: 'Al-Muzzammil',   meaning: 'The Enshrouded One',   verses: 20  },
  { number: 74,  arabic: 'المدثر',     english: 'Al-Muddaththir', meaning: 'The Cloaked One',      verses: 56  },
  { number: 75,  arabic: 'القيامة',    english: 'Al-Qiyamah',     meaning: 'The Resurrection',     verses: 40  },
  { number: 76,  arabic: 'الإنسان',    english: 'Al-Insan',       meaning: 'The Man',              verses: 31  },
  { number: 77,  arabic: 'المرسلات',   english: 'Al-Mursalat',    meaning: 'The Emissaries',       verses: 50  },
  { number: 78,  arabic: 'النبأ',      english: "An-Naba'",       meaning: 'The Tidings',          verses: 40  },
  { number: 79,  arabic: 'النازعات',   english: "An-Nazi'at",     meaning: 'Those Who Drag Forth', verses: 46  },
  { number: 80,  arabic: 'عبس',        english: 'Abasa',          meaning: 'He Frowned',           verses: 42  },
  { number: 81,  arabic: 'التكوير',    english: 'At-Takwir',      meaning: 'The Overthrowing',     verses: 29  },
  { number: 82,  arabic: 'الانفطار',   english: 'Al-Infitar',     meaning: 'The Cleaving',         verses: 19  },
  { number: 83,  arabic: 'المطففين',   english: 'Al-Mutaffifin',  meaning: 'The Defrauding',       verses: 36  },
  { number: 84,  arabic: 'الانشقاق',   english: 'Al-Inshiqaq',    meaning: 'The Sundering',        verses: 25  },
  { number: 85,  arabic: 'البروج',     english: 'Al-Buruj',       meaning: 'The Mansions of Stars',verses: 22  },
  { number: 86,  arabic: 'الطارق',     english: 'At-Tariq',       meaning: 'The Morning Star',     verses: 17  },
  { number: 87,  arabic: 'الأعلى',     english: "Al-A'la",        meaning: 'The Most High',        verses: 19  },
  { number: 88,  arabic: 'الغاشية',    english: 'Al-Ghashiyah',   meaning: 'The Overwhelming',     verses: 26  },
  { number: 89,  arabic: 'الفجر',      english: 'Al-Fajr',        meaning: 'The Dawn',             verses: 30  },
  { number: 90,  arabic: 'البلد',      english: 'Al-Balad',       meaning: 'The City',             verses: 20  },
  { number: 91,  arabic: 'الشمس',      english: 'Ash-Shams',      meaning: 'The Sun',              verses: 15  },
  { number: 92,  arabic: 'الليل',      english: 'Al-Layl',        meaning: 'The Night',            verses: 21  },
  { number: 93,  arabic: 'الضحى',      english: 'Ad-Duhaa',       meaning: 'The Morning Hours',    verses: 11  },
  { number: 94,  arabic: 'الشرح',      english: 'Ash-Sharh',      meaning: 'The Relief',           verses: 8   },
  { number: 95,  arabic: 'التين',      english: 'At-Tin',         meaning: 'The Fig',              verses: 8   },
  { number: 96,  arabic: 'العلق',      english: "Al-'Alaq",       meaning: 'The Clot',             verses: 19  },
  { number: 97,  arabic: 'القدر',      english: 'Al-Qadr',        meaning: 'The Power',            verses: 5   },
  { number: 98,  arabic: 'البينة',     english: 'Al-Bayyinah',    meaning: 'The Clear Proof',      verses: 8   },
  { number: 99,  arabic: 'الزلزلة',    english: 'Az-Zalzalah',    meaning: 'The Earthquake',       verses: 8   },
  { number: 100, arabic: 'العاديات',   english: "Al-'Adiyat",     meaning: 'The Courser',          verses: 11  },
  { number: 101, arabic: 'القارعة',    english: "Al-Qari'ah",     meaning: 'The Calamity',         verses: 11  },
  { number: 102, arabic: 'التكاثر',    english: 'At-Takathur',    meaning: 'The Rivalry in World Increase', verses: 8 },
  { number: 103, arabic: 'العصر',      english: "Al-'Asr",        meaning: 'The Declining Day',    verses: 3   },
  { number: 104, arabic: 'الهمزة',     english: 'Al-Humazah',     meaning: 'The Traducer',         verses: 9   },
  { number: 105, arabic: 'الفيل',      english: 'Al-Fil',         meaning: 'The Elephant',         verses: 5   },
  { number: 106, arabic: 'قريش',       english: 'Quraysh',        meaning: 'Quraysh',              verses: 4   },
  { number: 107, arabic: 'الماعون',    english: "Al-Ma'un",       meaning: 'The Small Kindnesses',  verses: 7  },
  { number: 108, arabic: 'الكوثر',     english: 'Al-Kawthar',     meaning: 'The Abundance',        verses: 3   },
  { number: 109, arabic: 'الكافرون',   english: 'Al-Kafirun',     meaning: 'The Disbelievers',     verses: 6   },
  { number: 110, arabic: 'النصر',      english: 'An-Nasr',        meaning: 'The Divine Support',   verses: 3   },
  { number: 111, arabic: 'المسد',      english: 'Al-Masad',       meaning: 'The Palm Fiber',       verses: 5   },
  { number: 112, arabic: 'الإخلاص',    english: 'Al-Ikhlas',      meaning: 'The Sincerity',        verses: 4   },
  { number: 113, arabic: 'الفلق',      english: 'Al-Falaq',       meaning: 'The Daybreak',         verses: 5   },
  { number: 114, arabic: 'الناس',      english: 'An-Nas',         meaning: 'Mankind',              verses: 6   },
] as const;
